version: 2.1
orbs:
  docker: circleci/docker@1.3.0
jobs:
  samtools_1.7-11-g041220d_diff:
    executor: docker/docker
    steps:
    - checkout
    - run_if_modified:
        pattern: samtools/latest/Dockerfile
        steps-to-run:
        - docker/build:
            image: kfdrc/samtools
            tag: latest
            path: samtools/latest/
            docker-context: samtools/latest/
  samtools_1.9_diff:
    executor: docker/docker
    steps:
    - checkout
    - run_if_modified:
        pattern: samtools/latest/Dockerfile
        steps-to-run:
        - docker/build:
            image: kfdrc/samtools
            tag: latest
            path: samtools/latest/
            docker-context: samtools/latest/
  samtools_1.6_diff:
    executor: docker/docker
    steps:
    - checkout
    - run_if_modified:
        pattern: samtools/latest/Dockerfile
        steps-to-run:
        - docker/build:
            image: kfdrc/samtools
            tag: latest
            path: samtools/latest/
            docker-context: samtools/latest/
  samtools_1.3.1_diff:
    executor: docker/docker
    steps:
    - checkout
    - run_if_modified:
        pattern: samtools/latest/Dockerfile
        steps-to-run:
        - docker/build:
            image: kfdrc/samtools
            tag: latest
            path: samtools/latest/
            docker-context: samtools/latest/
  samtools_latest_diff:
    executor: docker/docker
    steps:
    - checkout
    - run_if_modified:
        pattern: samtools/latest/Dockerfile
        steps-to-run:
        - docker/build:
            image: kfdrc/samtools
            tag: latest
            path: samtools/latest/
            docker-context: samtools/latest/
workflows:
  monthly:
    triggers:
    - schedule:
        cron: '* * 1 * *'
        filters:
          branches:
            only:
            - master
    jobs:
    - docker/publish:
        name: build_samtools_1.7-11-g041220d
        deploy: false
        image: kfdrc/samtools
        tag: 1.7-11-g041220d
        path: samtools/1.7-11-g041220d/
        docker-context: samtools/1.7-11-g041220d/
    - docker/publish:
        name: build_samtools_1.9
        deploy: false
        image: kfdrc/samtools
        tag: '1.9'
        path: samtools/1.9/
        docker-context: samtools/1.9/
    - docker/publish:
        name: build_samtools_1.6
        deploy: false
        image: kfdrc/samtools
        tag: '1.6'
        path: samtools/1.6/
        docker-context: samtools/1.6/
    - docker/publish:
        name: build_samtools_1.3.1
        deploy: false
        image: kfdrc/samtools
        tag: 1.3.1
        path: samtools/1.3.1/
        docker-context: samtools/1.3.1/
    - docker/publish:
        name: build_samtools_latest
        deploy: false
        image: kfdrc/samtools
        tag: latest
        path: samtools/latest/
        docker-context: samtools/latest/
  diff:
    jobs:
    - samtools_1.7-11-g041220d_diff
    - samtools_1.9_diff
    - samtools_1.6_diff
    - samtools_1.3.1_diff
    - samtools_latest_diff
