version: 2.1
orbs:
  docker: circleci/docker@1.3.0
workflows:
  samtools-monthly:
    triggers:
      - schedule:
         cron: "* * 1 * *"
         filters:
           branches:
             only:
               - master
    jobs:
      - docker/publish:
          deploy: false
          image: kfdrc/samtools
          tag: 1.9
          path: samtools/1.9/
      - docker/publish:
          deploy: false
          image: kfdrc/samtools
          tag: 1.6
          path: samtools/1.6/
