version: 2.1
orbs:
  docker: circleci/docker@1.3.0
  swissknife: roopakv/swissknife@0.48.0
workflows:
  monthly:
    triggers:
    - schedule:
        cron: '* * 1 * *'
        filters:
          branches:
            only:
            - master
    jobs:
    - docker/publish:
        name: samtools_1.7-11-g041220d_monthly
        deploy: false
        image: kfdrc/samtools
        tag: 1.7-11-g041220d
        path: samtools/1.7-11-g041220d/
        docker-context: samtools/1.7-11-g041220d/
    - docker/publish:
        name: samtools_1.9_monthly
        deploy: false
        image: kfdrc/samtools
        tag: '1.9'
        path: samtools/1.9/
        docker-context: samtools/1.9/
    - docker/publish:
        name: samtools_1.6_monthly
        deploy: false
        image: kfdrc/samtools
        tag: '1.6'
        path: samtools/1.6/
        docker-context: samtools/1.6/
    - docker/publish:
        name: samtools_1.3.1_monthly
        deploy: false
        image: kfdrc/samtools
        tag: 1.3.1
        path: samtools/1.3.1/
        docker-context: samtools/1.3.1/
    - docker/publish:
        name: samtools_latest_monthly
        deploy: false
        image: kfdrc/samtools
        tag: latest
        path: samtools/latest/
        docker-context: samtools/latest/
  diff:
    jobs:
    - docker/publish:
        name: samtools_1.7-11-g041220d_diff
        deploy: false
        image: kfdrc/samtools
        tag: 1.7-11-g041220d
        path: samtools/1.7-11-g041220d/
        docker-context: samtools/1.7-11-g041220d/
        before_build:
        - swissknife/run_if_modified:
            pattern: samtools/1.7-11-g041220d/Dockerfile
    - docker/publish:
        name: samtools_1.9_diff
        deploy: false
        image: kfdrc/samtools
        tag: '1.9'
        path: samtools/1.9/
        docker-context: samtools/1.9/
        before_build:
        - swissknife/run_if_modified:
            pattern: samtools/1.9/Dockerfile
    - docker/publish:
        name: samtools_1.6_diff
        deploy: false
        image: kfdrc/samtools
        tag: '1.6'
        path: samtools/1.6/
        docker-context: samtools/1.6/
        before_build:
        - swissknife/run_if_modified:
            pattern: samtools/1.6/Dockerfile
    - docker/publish:
        name: samtools_1.3.1_diff
        deploy: false
        image: kfdrc/samtools
        tag: 1.3.1
        path: samtools/1.3.1/
        docker-context: samtools/1.3.1/
        before_build:
        - swissknife/run_if_modified:
            pattern: samtools/1.3.1/Dockerfile
    - docker/publish:
        name: samtools_latest_diff
        deploy: false
        image: kfdrc/samtools
        tag: latest
        path: samtools/latest/
        docker-context: samtools/latest/
        before_build:
        - swissknife/run_if_modified:
            pattern: samtools/latest/Dockerfile
